# Generated by Django 5.2.7 on 2025-11-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
    ]
