# Generated by Django 5.2.7 on 2025-11-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('movie_id', models.BigIntegerField(db_index=True)),
                ('rating', models.FloatField()),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['movie_id'], name='reviews_rev_movie_i_8fea80_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user_id'], name='reviews_rev_user_id_a65d48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user_id', 'movie_id')},
        ),
    ]
