# Generated by Django 5.2.7 on 2025-11-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('genre_id', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
